### ISSUE TITLE
Fails when `devcontainer-feature.json` contains comments

### ISSUE THREAD

**Issue by snebjorn** [devcontainers/action#75]
devcontainers/action@v1 fails when **devcontainer-feature.json** contains comments.
```
SyntaxError: Unexpected token / in JSON at position 274
    at JSON.parse (<anonymous>)
    at packageCollection (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/collectionCommonUtils/packageCommandImpl.js:[17](https://github.com/snebjorn/devcontainer-feature/actions/runs/3211796200/jobs/5250216647#step:3:18)7:35)
    at async packageFeatureCollection (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/packageCommandImpl.js:49:12)
    at async doFeaturesPackageCommand (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/packageCommandImpl.js:26:26)
    at async featuresPublish (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/publish.js:72:22)
    at async /usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/featuresCLI/publish.js:45:[18](https://github.com/snebjorn/devcontainer-feature/actions/runs/3211796200/jobs/5250216647#step:3:19)
```

**Comment by joshspicer** [comment]
Since devcontainer.json is also very tolerant of comments, I agree that this file should behave similarly

**Comment by snebjorn** [comment]
The Dev Container spec says:

> It follows the JSON with Comments (jsonc) format.
> [source](https://containers.dev/implementors/json_reference/)

So it's not just tolerated, it's supported 😄

**Comment by joshspicer** [comment]
This should be fixed up stream with https://github.com/devcontainers/cli/issues/214 when this is released (this action will pull the latest CLI published to npm). 

Thanks for raising!

**Comment by samruddhikhandale** [comment]
Closing as fixed via https://github.com/devcontainers/cli/issues/214
